name: Deploy notification Service to K3s

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mash02/notification-service
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create notification-service-deployment.yaml
        shell: bash
        run: |
          cat <<EOF > notification-service-deployment.yaml
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: notification-service
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: notification-service
            template:
              metadata:
                labels:
                  app: notification-service
              spec:
                containers:
                - name: notification-service
                  image: ${IMAGE_NAME}:${IMAGE_TAG}
                  ports:
                  - containerPort: 8084
                  envFrom:
                  - secretRef:
                      name: notification-service-secret
          EOF

      - name: Write notification-service-secret.yaml from GitHub Secret
        run: |
          echo "${{ secrets.NOTIFICATION_SERVICE_SECRET_YAML_BASE64 }}" | base64 -d > notification-service-secret.yaml

      - name: Check if files exist
        run: |
          ls -la
          echo "notification-service-deployment.yaml:" && cat notification-service-deployment.yaml
          echo "notification-service-secret.yaml:" && cat notification-service-secret.yaml || echo "Missing secret file"

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Install OpenSSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH key (RSA)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} "mkdir -p ~/deploy/notification-service"
          scp notification-service-*.yaml ubuntu@${{ secrets.EC2_HOST }}:~/deploy/notification-service/
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/deploy/notification-service
            sudo kubectl apply -f notification-service-secret.yaml
            sudo kubectl apply -f notification-service-deployment.yaml
          EOF
